------------------------------------------
Running Starter Tests
Starter Tests: 14/14 passed.
----
Starter Tests Mark: 3.00/3
------------------------------------------

------------------------------------------
Running Hidden Tests
Hidden Correctness Tests Part 1: 0/13 passed.
Hidden Correctness Tests Part 2: 2/2 passed
Overall Hidden Tests: 2/15
----
Hidden Tests Mark: 0.80/6
------------------------------------------

------------------------------------------------------------------------------------
Correctness Mark Overall: 3.80/9.
------------------------------------------------------------------------------------
